language: node_js
node_js:
  - "10"
cache: yarn

dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libjson-perl libperlio-gzip-perl libgd-perl libjson-perl pandoc
  - (curl -L http://cpanmin.us | sudo perl - --self-upgrade) && sudo cpanm Pandoc
  - curl -OL http://current.geneontology.org/metadata/GO.xrf_abbs
  - curl -OL https://raw.githubusercontent.com/pombase/pombase-config/master/website/pombase_v2_config.json
  - yarn

script:
  - cp etc/example_minimal_jbrowse_track_list.json minimal_jbrowse_track_list.json
  - ./etc/update_generated_files.sh GO.xrf_abbs pombase_v2_config.json && ./node_modules/@angular/cli/bin/ng build
