language: node_js
node_js:
  - "10"
cache: yarn

dist: xenial
before_install:
  - curl -OL http://current.geneontology.org/metadata/GO.xrf_abbs
  - curl -IL https://raw.githubusercontent.com/pombase/pombase-config/master/website/pombase_v2_config.json
  - yarn
script:
  - ./etc/update_generated_files.sh GO.xrf_abbs pombase_v2_config.json
  - ./node_modules/@angular/cli/bin/ng build
